name: Build and Deploy to Azure Container Apps

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  REGISTRY_NAME: aiwebsitecreator
  CONTAINER_APP_NAME: ca-tf-nlp-service
  CONTAINER_APP_RESOURCE_GROUP: Sandboxing
  REGISTRY_LOGIN_SERVER: aiwebsitecreator.azurecr.io
  CONTAINER_APP_CONTAINER_NAME: tf-nlp-service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Build and push container image to registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build and push image
      run: |
        docker build . -t ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_APP_CONTAINER_NAME }}:${{ github.sha }}
        docker push ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_APP_CONTAINER_NAME }}:${{ github.sha }}

    - name: Deploy to Azure Container Apps
      uses: azure/container-apps-deploy-action@v1
      with:
        resourceGroup: ${{ env.CONTAINER_APP_RESOURCE_GROUP }}
        containerAppName: ${{ env.CONTAINER_APP_NAME }}
        imageToDeploy: ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_APP_CONTAINER_NAME }}:${{ github.sha }}
